metric: COCO
num_classes: 5

TrainDataset: !COCODataSet
  image_dir: data
  anno_path: labels.json
  dataset_dir: content/test_destination_COCO
  data_fields: ["image", "gt_bbox", "gt_class", "is_crowd"]

EvalDataset: !COCODataSet
  image_dir: data
  anno_path: labels.json
  dataset_dir: content/test_destination_COCO
